[build]
command = "yarn app build"
publish = "workspaces/app/.next"

[functions]
included_files = ["node_modules/microtime/prebuilds/**"]

[[plugins]]
package = "@netlify/plugin-nextjs"
[[plugins]]
package = "netlify-plugin-contextual-env"